# Setup
title:               Collegiate Quizbowl Packets
tagline:             ''
description:         'Collegiate Quizbowl Packets'
url:                 http://ryanrosenberg.github.io
baseurl:             'http://ryanrosenberg.github.io'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ryan Rosenberg
  url:               https://twitter.com/rosenbergry
  email:             ryanr345@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: #UA-XXXX-Y
